# Generated by Django 5.0.2 on 2024-02-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
